export const RESUME = {
  name: "Lukas Sorensen",
  title: "Full Stack Software Engineer",
  summary:
    "Senior Full Stack Web Developer with 10+ years delivering production software across startup, mid-sized, and contract environments. My focus combines AI systems and full-stack engineering.",
  contact: {
    email: "lukasasorensen@gmail.com",
    website: "lukasasorensen.com",
    github: "github.com/lukasasorensen",
    linkedin: "linkedin.com/in/lukasasorensen",
  },
  experience: [
    {
      company: "Sportsdigita",
      title: "Senior Full Stack & Lead Engineer",
      period: "October 2023 - Present",
      highlights: [
        "Architected and built DIGIDECK’s presentation design editor and custom web component framework, enabling developers to create compatible presentation elements through an SDK and CLI, and users to arrange them into slide layouts with drag-and-drop controls, snapping, anchoring, and resizing.",
        "Led technical architecture for DIGIDECK’s design editor, component framework, and AI assistant; guided an offshore engineering team in India building DIGIDECK Components and mentored onshore junior developers through code reviews and one-on-one pairing sessions.",
        "Built AI-assisted workflows that redesign slides and apply changes across decks of 100+ slides, completing updates in approximately 1–3 hours that previously required 1–4 days of in-house design work.",
        "Integrated AI tools and reusable workflows using Claude, Cursor, OpenAI, and Rovo to support code generation, automate code reviews, and monitor security issues across the engineering team.",
      ],
    },
    {
      company: "Sportsdigita",
      title: "Full Stack Engineer",
      period: "November 2018 - October 2023",
      highlights: [
        "Delivered product updates and new features to the DIGIDECK Presentation platform on both the **AngularJS** frontend and **NodeJS, Express & MongoDB** backend.",
        "Improved platform reliability through bug fixes and security updates, contributing to DIGIDECK’s company-reported 99.99% uptime.",
        "Developed and maintained CI/CD pipelines and **AWS** deployment workflows to support reliable production releases and efficient development processes.",
      ],
    },
    {
      company: "SideShift",
      title: "Architect Consultant",
      period: "February 2024 - May 2024",
      highlights: [
        "Defined scalable architecture and technical direction for a cross-platform React Native app (Web, iOS, Android) built with Expo and Postgres.",
        "Produced implementation standards and documentation for clean handoff to the internal engineering team.",
      ],
    },
    {
      company: "Union App LLC",
      title: "Full Stack Engineer",
      period: "January 2016 - November 2018",
      highlights: [
        "Built a social platform for US unions with Angular/TypeScript and NodeJS/MongoDB, delivering end-to-end product functionality.",
        "Implemented backend APIs and AWS deployment workflows to support reliable production releases.",
      ],
    },
  ],
  skills: [
    "AI",
    "Claude Code, Cursor",
    "OpenAI",
    "Ollama",
    "MCP",
    "Agentic Workflows",
    "TypeScript",
    "JavaScript",
    "React",
    "React Native",
    "NextJS",
    "Vue",
    "Angular",
    "NodeJS",
    "MongoDB",
    "Postgres",
    "Redis",
    "AWS",
    "Docker",
    "CI/CD",
    "Git",
    "Webpack",
    "Vite",
    "Tailwind CSS",
    "SOLID / OOP principles",
    "Agile / JIRA",
  ],
  projects: [
    {
      title: "DIGIDECK AI Assistant",
      description:
        "Architected and implemented DIGIDECK AI Assistant workflows that connect domain-specific deck knowledge to MCP tools and direct editor actions, enabling governed generation, slide-level updates, and large multi-slide edits in minutes rather than hours or days.",
      company: "Sportsdigita",
      skills: [
        "Claude",
        "OpenAI",
        "Ollama",
        "LangChain",
        "Model Context Protocol (MCP)",
        "TypeScript",
        "NodeJS",
        "Agent Orchestration",
        "Tool Calling",
        "Observability/Governance",
      ],
      link: "https://www.thedigideck.com/ai/",
    },
    {
      title: "DIGIDECK Components",
      description:
        "Architected a modular JavaScript Framework extending the Custom Web Components API, allowing internal and external developers to create presentation plugins. Includes a CLI to bootstrap new plugin apps, a digideckCORE API, and a Docusaurus documentation site with Algolia search.",
      company: "Sportsdigita",
      skills: ["JavaScript", "NodeJS", "NPM", "Webpack", "Custom Web Components", "MongoDB", "ExpressJS", "Redis"],
      link: "https://www.thedigideck.com/customize/",
    },
    {
      title: "DIGIDECK Design Editor",
      description:
        "Architected and developed a Photoshop/Canva-like WYSIWYG editor in TypeScript allowing users to drag, resize, move, and rotate plugins on presentations. Features grid snapping, relative snapping, anchoring, percentage units, and multiple media queries.",
      company: "Sportsdigita",
      skills: ["TypeScript", "NodeJS", "Webpack", "SOLID/OOP", "CI/CD", "Git"],
      link: "https://www.thedigideck.com/design/",
    },
    {
      title: "SideShift Mobile App",
      description:
        "Led architecture for a React Native job board and social app for college students, delivered across Web, iOS, and Android with a maintainable handoff plan.",
      company: "SideShift",
      skills: ["TypeScript", "React Native", "Expo", "PostgreSQL", "Supabase", "Git", "Xcode", "Adobe XD"],
      link: "https://www.sideshiftjobs.com/",
    },
  ],
};
